Models/User.cs
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BTL_WEB_NC.Models
{
    public class User
    {
        [Key]
        public Guid Id { get; set; }
        [Column(TypeName = "nvarchar(200)")]
        public string? Name { get; set; }
        [Column(TypeName = "varchar(15)")]
        public string? PhoneNumber { get; set; }
        [Column(TypeName = "varchar(100)")]
        public string? Email { get; set; }
        [Column(TypeName = "nvarchar(10)")]
        public string? Gender { get; set; }
        [Column(TypeName = "varchar(1000)")]
        public string? Password { get; set; }
        [Column(TypeName = "varchar(20)")]
        public string? RoleId { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

    }
}

ViewModels/UserInfoHouseBookingViewModel.cs
using BTL_WEB_NC.Models;
using BTL_WEB_NC.ViewModels;


public class UserInfoHouseBookingViewModel
{
    public User? user { get; set; }
    public List<BookingViewModel>? bookingList { get; set; }
}

Controllers/AdminController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using BTL_WEB_NC.Models;
using static BTL_WEB_NC.Controllers.AdminController;
using BTL_WEB_NC.Data;

namespace BTL_WEB_NC.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationContext _context;

        public AdminController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult HouseManage()
        {
            if (HttpContext.Session.GetString("Role") == "role1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("UserInfo", "User");
            }

        }

        //TreeView=======================================================================================
        [HttpPost]
        public JsonResult RootsTreeView()
        {

            List<Location> roots = new List<Location>();
            roots = _context.Locations.Where(a => a.ParentId.Equals("#")).OrderBy(a => a.Name).ToList();
            return Json(roots);
        }

        [HttpPost]
        public JsonResult GetTreeView(string pid)
        {
            List<Location> subNodes = new List<Location>();

            subNodes = _context.Locations.
                Where(a => a.ParentId.Equals(pid)).OrderBy(a => a.Name).ToList();

            return Json(subNodes);
        }


        //DataTable=====================================================================================
        [HttpPost]
        public string getDataTables(string locationId)
        {
            List<House> listHouse = _context.Houses.Where(a => a.OfLocationId.Contains(locationId)).ToList();
            var value = JsonConvert.SerializeObject(new { data = listHouse });
            return value;
        }


        //Thêm mới=======================================================================================
        public class HouseAndImageCategory
        {
            public House? houseObject { get; set; }
            public ImageCategory? imageCategoryObject { get; set; }
        }

        [HttpPost]
        public async Task<int> ThemMoi([FromBody] HouseAndImageCategory houseAndImageCategory)
        {
            var result = -1;
            try
            {
                _context.Houses.Add(houseAndImageCategory.houseObject);

                var houseId = houseAndImageCategory.houseObject.Id;

                var urls = houseAndImageCategory.imageCategoryObject.Url;
                if (urls.EndsWith(";"))
                {
                    urls = urls.Remove(urls.Length - 1);
                }

                foreach (var url in urls.Split(';'))
                {
                    var imageCategory = new ImageCategory
                    {
                        HouseId = houseId,
                        Url = url
                    };
                    _context.ImageCategories.Add(imageCategory);
                }

                await _context.SaveChangesAsync();
                result = 1;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                result = 0;
            }
            return result;
        }



        // Chi tiết======================================================================================
        public class ListHouseAndImageCategory
        {
            public List<House>? Houses { get; set; }
            public List<ImageCategory>? ImageCategories { get; set; }
        }
        [HttpGet]
        public JsonResult ChiTiet(Guid houseId)
        {
            var data = new ListHouseAndImageCategory();

            data.Houses = _context.Houses.
                Where(a => a.Id.Equals(houseId)).ToList();
            data.ImageCategories = _context.ImageCategories.
                Where(a => a.HouseId.Equals(houseId)).ToList();

            return Json(data);
        }



        // Cập nhật========================================================================================
        [HttpPost]
        public async Task<int> CapNhat([FromBody] HouseAndImageCategory houseAndImageCategory)
        {
            var result = -1;

            try
            {
                _context.Houses.Update(houseAndImageCategory.houseObject);
                var imageCategoriesToDelete = _context.ImageCategories.Where(ic => ic.HouseId == houseAndImageCategory.houseObject.Id);
                _context.ImageCategories.RemoveRange(imageCategoriesToDelete);

                var houseId = houseAndImageCategory.houseObject.Id;

                var urls = houseAndImageCategory.imageCategoryObject.Url;
                if (urls.EndsWith(";"))
                {
                    urls = urls.Remove(urls.Length - 1);
                }

                foreach (var url in urls.Split(';'))
                {
                    var imageCategory = new ImageCategory
                    {
                        HouseId = houseId,
                        Url = url
                    };
                    _context.ImageCategories.Add(imageCategory);
                }

                //_context.ImageCategories.Update(houseAndImageCategory.imageCategoryObject);
                await _context.SaveChangesAsync();
                result = 1;
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!HouseExists(houseAndImageCategory.houseObject.Id))
                {
                    result = 0;
                }
                else
                {
                    throw;
                }
            }
            return result;
        }

        // Xóa=====================================================================================================
        [HttpPost]

        public async Task<int> DeleteConfirmed(Guid houseId)
        {
            var result = -1;
            var house = await _context.Houses.FindAsync(houseId);
            if (house != null)
            {
                _context.Houses.Remove(house);
                var imageCategoriesToDelete = _context.ImageCategories.Where(ic => ic.HouseId == houseId);
                _context.ImageCategories.RemoveRange(imageCategoriesToDelete);
                await _context.SaveChangesAsync();
                result = 1;
            }
            else
            {
                result = 0;
            }

            return result;
        }


        private bool HouseExists(Guid houseId)
        {
            return (_context.Houses?.Any(e => e.Id == houseId)).GetValueOrDefault();
        }

    }
}

// Câu hỏi thi
// 1. Chọn một bảng của một sản phẩm/dịch vụ/người dùng mà bạn phụ trách. Tạo một view mới hiển thị tất cả các trường thông tin của các bản ghi: 
//      + Đối với desktop thì hiển thị 3 bản ghi trên một hàng
//      + Mobile thì 1 bản ghi trên 1 hàng
// 2. Thêm trường VerifyKey cho bảng vừa chọn có kiểu dữ liệu string, yêu cầu phải có 10 kí tự và bắt đầu bằng chữ số trong Model
// 3. Thêm/Thay đổi một chức năng để có thể thêm dữ liệu cho trường VerifyKey này. Hiển thị dữ liệu VerifyKey trên các bản ghi của view vừa tạo
// 4. Đánh giá công tác làm việc nhóm     

Controllers/BookingCalenderController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using BTL_WEB_NC.Models;
using BTL_WEB_NC.Data;
using BTL_WEB_NC.ViewModels;
using static BTL_WEB_NC.Controllers.AdminController;

namespace BTL_WEB_NC.Controllers
{
    public class BookingCalenderController : Controller
    {
        private readonly ApplicationContext _context;

        public BookingCalenderController(ApplicationContext context)
        {
            _context = context;
        }

        public IActionResult BookingCalenderView()
        {
            if (HttpContext.Session.GetString("Role") == "role1")
            {
                return View();
            }
            else
            {
                return RedirectToAction("UserInfo", "User");
            }
        }


        /*
        public ActionResult ModifyNoteBookingCalender(Guid bookingId, string note)
        {
            var bookingCalender = _context.BookingCalenders.FirstOrDefault(b => b.Id == bookingId);
            if (bookingCalender != null)
            {
                bookingCalender.Note = note;
                _context.SaveChanges();
                return RedirectToAction("UserInfoHouseBooking", "User");
            }
            else
            {
                return RedirectToAction("UserInfoHouseBooking", "User");
            }
        }
        */
        [HttpPost]
        public async Task<int> ModifyNoteBookingCalender([FromBody] BookingUpdateModel model)
        {
            var result = -1;
            try
            {
                var booking = await _context.BookingCalenders.FindAsync(model.BookingId);
                if (booking != null)
                {
                    booking.Note = model.Note;
                    await _context.SaveChangesAsync();
                }

                result = 1;
            }
            catch (DbUpdateConcurrencyException)
            {
                result = 0;
            }
            return result;
        }
        //DataTable=====================================================================================
        [HttpGet]
        public JsonResult GetBookings()
        {
            var bookingDetails = (from bc in _context.BookingCalenders
                                  join u in _context.Users on bc.CustomerId equals u.Id
                                  join h in _context.Houses on bc.HouseId equals h.Id
                                  select new
                                  {
                                      bookingId = bc.Id,
                                      houseId = h.Id,
                                      houseType = h.HouseType,
                                      housePrice = h.Price,
                                      houseStatus = h.HouseStatus,
                                      customerId = u.Id,
                                      customerName = u.Name,
                                      customerPhone = u.PhoneNumber,
                                  }).ToList();
            return Json(new { data = bookingDetails });
        }



        //Chi tiết=====================================================================================
        [HttpGet]
        public JsonResult ChiTiet(Guid bookingCalendersId)
        {
            var bookingDetails = (from bc in _context.BookingCalenders
                                  join u in _context.Users on bc.CustomerId equals u.Id
                                  join h in _context.Houses on bc.HouseId equals h.Id
                                  join l in _context.Locations on h.OfLocationId equals l.Id
                                  where bc.Id == bookingCalendersId
                                  select new
                                  {
                                      bookingId = bc.Id,
                                      bookingNote = bc.Note,

                                      customerName = u.Name,
                                      customerPhone = u.PhoneNumber,
                                      customerEmail = u.Email,

                                      houseTitle = h.HouseTitle,
                                      ownerName = h.OwnerName,
                                      ownerPhone = h.OwnerPhone,
                                      address = h.Address,
                                      acreage = h.Acreage,
                                      price = h.Price,
                                      description = h.Desciption,
                                      houseType = h.HouseType,

                                      locationName = l.Name

                                  }).ToList();

            return Json(bookingDetails);
        }

        // Cập nhật HouseStatus=====================================================================================================
        [HttpPost]
        public async Task<int> UpdateHouseStatus([FromBody] House houseObject)
        {
            var result = -1;
            var house = await _context.Houses.FindAsync(houseObject.Id);
            if (house != null)
            {

                house.HouseStatus = houseObject.HouseStatus;
                _context.Update(house);
                await _context.SaveChangesAsync();
                result = 1;
            }
            else
            {
                result = 0;
            }

            return result;
        }

        // Xóa=====================================================================================================
        [HttpPost]
        public async Task<int> DeleteConfirmed(Guid bookingCalendersId)
        {
            var result = -1;
            var bc = await _context.BookingCalenders.FindAsync(bookingCalendersId);
            if (bc != null)
            {
                _context.BookingCalenders.Remove(bc);
                await _context.SaveChangesAsync();
                result = 1;
            }
            else
            {
                result = 0;
            }

            return result;
        }

    }
}

Views/User/UserInfo.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model User
}
<div class="user-info col-lg-8 ">
    <div class="user-info-row-1 ">
        <div class="img-user">
            @if (Context.Session.GetString("Role") == "role1")
            {
                <img src="~/images/image_admin.jpg" />
            }
            else
            {
                <img src="~/images/image_user.jpg" />
            }
            <p>@Model.Name</p>
        </div>
       <div class="list-info-user">
           <ul>
                <li><i class="far fa-user"></i> Thông tin tài khoản</li>
                <a href="/User/UserInfoHouseBooking">
                <li><i class="fas fa-home"></i>Danh sách phòng đặt lịch</li>
                </a>
           </ul>
       </div>
    </div>
    <div class="user-info-row-2 ">
        <div class="title-user">
            <h1>Thông tin tài khoản</h1>
        </div>
        <div class="text-info-user">
            <table class="table table-striped">
                <tbody>
                    <tr>
                        <td>
                            Họ tên:
                        </td>
                        <td>
                            @Model.Name
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Email
                        </td>
                        <td>
                            @Model.Email
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Số điện thoại
                        </td>
                        <td>
                            @Model.PhoneNumber
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Giới tính
                        </td>
                        <td>
                            <p>@Model.Gender</p>
                        </td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

Views/User/UserInfoHouseBooking.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    @model UserInfoHouseBookingViewModel

}
<div class="user-info-booking col-lg-12 ">
    <div class=" user-info-booking-row-1 ">
        <div class="img-user">
            @if (Context.Session.GetString("Role") == "role1")
            {
                <img src="~/images/image_admin.jpg" />
            }
            else
            {
                <img src="~/images/image_user.jpg" />
            }
            <p>@Model.user.Name</p>
        </div>
        <div class="list-info-user">
            <ul>
                <li><i class="far fa-user"></i>  <a href="/User/UserInfo"> Thông tin tài khoản</a></li>
                <li><i class="fas fa-home"></i>Danh sách phòng đặt lịch</li>
            </ul>
        </div>
    </div>
    <div id="ModifiedModal" style="font-size:1.5rem" class="modal fade" tabindex="-1">
        <div class="modal-dialog modal-lg">
            <div class="modal-content">
                <form id="form">
                    <div class="modal-body">
                        <h6 style="color:#0481A0">Ghi Chú:</h6>
                        <textarea id="note" name="note" class="form-control" rows="3"></textarea>
                        <input type="hidden" id="bookingIdInput" name="bookingId" />
                    </div>
                </form>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Hủy</button>
                    <button type="submit" id="editNoteBooking" class="btn btn-primary">Sửa</button>
                </div>
            </div>
        </div>
    </div>
    <div class="user-info-booking-row-2  ">
        <div class="title-user">
            <h1>Danh sách phòng đặt lịch</h1>
        </div>
        <div class="text-info-user-booking">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>Tên phòng</th>
                        <th>Địa chỉ</th>
                        <th>Giá</th>
                        <th>Ngày đặt</th>
                        <th>Ghi chú</th>
                        <th>Thao tác</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var booking in @Model.bookingList)
                    {
                        <tr>
                            <td>@booking.houseName</td>
                            <td>@booking.houseAddress</td>
                            <td>@booking.housePrice</td>
                            <td>@booking.houseCreatedAt</td>
                            <td>@booking.houseTittle</td>
                            <td>
                                <i id="edit-house-booking" class="far fa-edit modifile" data-booking-id="@booking.bookingId"></i>
                                <i onclick="DeleteBooking('@booking.bookingId.ToString("D")')" id="delete-house-booking" class="fas fa-trash-alt" data-booking-id="@booking.bookingId"></i>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    function DeleteBooking(bookingId) {
        if (confirm("Bạn có chắc muốn xóa phòng này ko ?")) {
            window.location.href = "/User/DeleteBooking?bookingId=" + bookingId;
        }
    }
    $(document).ready(function () {
        $('.modifile').click(function () {
            var bookingId = $(this).data('booking-id');
            $('#bookingIdInput').val(bookingId);
            $('#ModifiedModal').modal('show');
        });

        $('#editNoteBooking').click(function (e) {
            e.preventDefault();
            var bookingId = $('#bookingIdInput').val();
            var note = $('#note').val().trim();

            if (!note) {
                alert("Vui lòng điền ghi chú!");
                return;
            }
           
            var data = JSON.stringify({
                BookingId: bookingId,
                Note: note
            });

            $.ajax({
                url: '/BookingCalender/ModifyNoteBookingCalender',
                type: 'POST',
                contentType: 'application/json',
                data: data,
                success: function (result) {
                    if (result === 1) {
                        alert('Cập nhật thành công!');
                        $('#ModifiedModal').modal('hide');
                    } else {
                        alert('Cập nhật thất bại!');
                    }
                },
                error: function (xhr, status, error) {
                    alert(xhr.responseText);
                    console.log(xhr.responseText)
                }
            });
        });
    });

</script>

Views/User/UserManage.cshtml
<div class="containerProject">
    <div class="contentBlock">
        <div class="contentBlock__heading">
            <a asp-controller="Admin" asp-action="HouseManage">
                <i class="fa fa-list"></i>
                Danh sách phòng
            </a>
            <a asp-controller="BookingCalender" asp-action="BookingCalenderView">
                <i class="fa fa-star"></i>
                Phòng đang chờ được xem
            </a>
            <a style="color: #049363; font-weight: 600; border-bottom: 3px solid #049363">
                <i class="fa fa-user-friends"></i>
                Người dùng
            </a>
        </div>
        <div class="contentBlock__container">
            <div class="contentBlock__content2">
                @*Container content*@
            </div>
        </div>
    </div>
</div>

<!-- Modal CRUD-->
<div class="modal fade" id="myModalCRUD" role="dialog">
    <div class="modal-dialog">

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body">
                <form id="form">
                    <div class="form-group inputBlock">
                        <label for="Name">Họ và tên</label>
                        <input type="text" class="form-control inputContent" id="Name" name="Name" placeholder="" />
                    </div>
                    <div class="form-group inputBlock">
                        <label for="PhoneNumber">Số điện thoại</label>
                        <input type="text" class="form-control inputContent" id="PhoneNumber" name="PhoneNumber" placeholder="" />
                    </div>
                    <div class="form-group inputBlock">
                        <label for="Email">Email</label>
                        <input type="text" class="form-control inputContent" id="Email" name="Email" placeholder="" />
                    </div>
                    <div class="form-group inputBlock">
                        <label for="Password">Mật khẩu</label>
                        <input type="text" class="form-control inputContent" id="Password" name="Password" placeholder="" />
                    </div>
                    <div class="form-group inputBlock">
                        <label for="Gender">Giới tính</label>
                        <select name="Gender" id="Gender" class="form-control selectContent">
                            <option value="Nam" selected>Nam</option>
                            <option value="Nữ">Nữ</option>
                        </select>
                    </div>
                    <div class="form-group inputBlock">
                        <label for="Role">Quyền</label>
                        <select name="Role" id="Role" class="form-control selectContent">
                            <option value="role1">Admin</option>
                            <option value="role2" selected>Customer</option>
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" id="btnUpdate" style="display: none">Cập nhật</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>

    </div>
</div>

<!-- Modal InfoBooking-->
<div class="modal fade" id="myModalListBooking" role="dialog">
    <div class="modal-dialog" style="min-width: 75%"  >

        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Modal Header</h4>
            </div>
            <div class="modal-body bodyModalView">
                @*Table list booking*@
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
            </div>
        </div>

    </div>
</div>

<script src="~/js/userManage.js"></script>